### ISSUE TITLE
Empty iptables on start OpenWrt LXC

### ISSUE THREAD

**Issue by ghost** [DazzyWalkman/oplxc4pve#1]
First of all, thanks for this great script.
Of all the scripts/methods i tried for getting OpenWrt to work, yours is definitely the easiest.

Now the issue (tested with stable 19.07.5 and snapshot):

I create a new container (all default parameters) via the script. Add eth0 and eth1 via the Proxmox gui.
Then i start the lxc container and change the lan ip in /etc/config/network and reboot.

After the reboot i can login via the Luci web interface.   

When I look at the firewall tab, no rules are present. When I manually restart the firewall via "/etc/init.d/firewall restart" the firewall rules get inserted.

Do you have the same issue? I can work around it by running the restart command in the OpenWrt startup.
But it would be nice to have this working out of the box.

**Comment by DazzyWalkman** [comment]
No, I don't experience the issue. 

Probably because I use https://github.com/DazzyWalkman/lxd-openwrt-simplified to patch my tarballs before deploy.

You may also be interested to look at https://github.com/mikma/lxd-openwrt if you are using image builder.

Or simply inject any customed settings you like to the /etc/ dir of the tarball manually. Please refer to the /files dir of the repos mentioned above.

**Comment by ghost** [comment]
Tnx, i will try and use your other script first.
